base:
  epochs: 100
  batch_size: 128
  start_epoch: 0
  weight_decay: 5e-4
  lr: 0.1
  print_freq: 1000
  seed: 2000
  nprocs: 0
  local_rank: 0
  workers: 8
  log: none
  project: none
  port: '12345'
  gpu_id: '1'
  data: cifar10-dvs
  model: vgg
  # dataset_path: ./datasets
  dataset_path: /LOCAL/dengyu/dvs_dataset/dvs-cifar10-1
  

snn-test:
  T: 10
  sigma: 1.0
  mode: 'cutoff'
  model_path: /LOCAL2/dengyu/MySNN/easycutoff/outputs/2023-12-08/07-55-17/cifar10-dvs-vggann-alpha0.002.pth

logging:
  wandb_logging: 'False'
  tensorboard_logging: 'False'
  comet_logging: 'False'
  run_dir: none

###  Disable Hydra Logging ###x
defaults:
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

hydra:  
  output_subdir: null  
  run:  
    dir: .